ARG version
FROM almalinux:${version:-8}
ARG COURSE=Docker
ARG TRAINER=Siva
ARG Duration=120HRS
ENV Duration=${Duration}
RUN echo "course is: ${COURSE}, Trainer is: ${TRAINER}, Duration is:${Duration}"
CMD ["sleep","100"]